Repository Itaseki/itaseki-front, pull requests merged in 2022-07, with the labels that each got.

#22 [FEAT] 영상페이지에서 플레이리스트 조회&담기&추가
  src/Assets/Add_new_video.png
  src/Components/Video/YoutubeAPI.js
  src/Components/Video/YoutubeIframe.js
  src/Pages/Video/AddNewVideo.js
  src/Pages/Video/AllVideo.js
  src/Style/Video.js
  src/index.css
  src/preURL/preURL.js
Labels: 영상게시판, feat

#24 [Design] 달리기방 레이아웃, 라이트/다크모드
  src/App.js
  src/Assets/Chat_Inform.png
  src/Assets/Chat_Inform_Arrow.png
  src/Assets/Chat_Inform_icon.png
  src/Assets/Chat_Seding_btn.png
  src/Assets/Exit_Dark.png
  src/Assets/Exit_Light.png
  src/Assets/Switch_Dark.png
  src/Assets/Switch_Light.png
  src/Pages/Run/Running.js
  src/Style/Running.js
  src/index.css
Labels: design, 달리기방

#32 [HOTFIX] 전체영상게시판 영상 목록 4개씩 나타내기 수정
  src/Components/PlaylistToggle.js
  src/Pages/Video/AddNewVideo.js
  src/Pages/Video/AllVideo.js
  src/Style/Video.js
Labels: 영상게시판, fix

#34 [FEAT/DESIGN] 플레이리스트 게시판
  src/App.js
  src/Assets/Add_New_Ply.png
  src/Assets/Best_Ply.png
  src/Assets/Best_Video_TV.png
  src/Assets/Line_info.png
  src/Assets/Ply_Count_Icon.png
  src/Assets/Ply_preview.png
  src/Assets/Stored_Ply.png
  src/Pages/Playlist/AllPlaylist.js
  src/Pages/Video/AllVideo.js
  src/Style/Playlist.js
  src/Style/Video.js
Labels: feat, design, 플레이리스트

#36 [FEAT] 메인 페이지 하단 Wrapper(미완)
  src/Components/Main/OneVideo.js
  src/Components/Main/Oneply.js
  src/Pages/Main.js
Labels: feat, design

#38 [FIX] 필요 없는 변수 정리, 오타 수정
  src/Components/Main/OneVideo.js
  src/Components/Main/Oneply.js
Labels: bug, fix

#39 [DESIGN] 영상게시판 최종 디자인 수정
  src/Assets/Add_video_submit.png
  src/Components/Pagination.js
  src/Pages/Video/AddNewVideo.js
  src/Pages/Video/AllVideo.js
  src/Pages/Video/VideoDetail.js
  src/Style/Community.js
  src/Style/Video.js
Labels: 영상게시판, design

#41 [FEAT/DESIGN] 필요 없는 변수 정리, 오타 수정
  src/Assets/Best_GIF.png
  src/Pages/Board/GIFBoard.js
  src/Pages/Board/GIFBoardDetail.js
Labels: bug, feat, design, fix

#43 [FEAT/DESIGN] 메인 이미지 경로 수정/카테고리 바 순서 변경
  src/Components/Header.js
  src/Pages/Main.js
Labels: feat, design

#45 [DESIGN] 구독 플레이리스트 게시판 디자인
  .env
  .gitignore
  src/App.js
  src/Assets/Subscribed_ply.png
  src/Pages/Playlist/AllPlaylist.js
  src/Pages/Playlist/SubscribedPly.js
  src/Pages/Video/VideoDetail.js
  src/Style/Playlist.js
Labels: design, 플레이리스트

#46 [FEAT] 구독 플레이리스트 조회, 토큰값 리턴 컴포넌트 생성
  src/Components/Token.js
  src/Pages/Playlist/SubscribedPly.js
Labels: feat, 플레이리스트

#47 [FEAT/DESIGN] 다음 달리기 영상 조회 추가(상단 Wrapper)
  src/Assets/Nothing.png
  src/Pages/Run/Reservation.js
  src/Pages/Run/ReservationList.js
Labels: feat, design

#48 [REFACTOR] 단일 영상 컴포넌트, 단일 플레이리스트 컴포넌트
  src/Components/Main/OneVideo.js
  src/Components/Playlist/Oneply.js
  src/Components/Playlist/PlaylistToggle.js
  src/Components/Video/OneVideo.js
  src/Pages/Main.js
  src/Pages/Playlist/AllPlaylist.js
  src/Pages/Playlist/SubscribedPly.js
  src/Pages/Video/AddNewVideo.js
  src/Pages/Video/AllVideo.js
Labels: refactor

#49 [FEAT/DESIGN] 오늘의 예약 확정 목록 조회/타임테이블 추가(하단 Wrapper)
  src/Assets/Ticket.png
  src/Pages/Run/AddReserv.js
  src/Pages/Run/Reservation.js
  src/Pages/Run/ReservationList.js
  src/Pages/Run/TimeTable.js
Labels: feat, design

#51 [FEAT/DESIGN] 새 짤글 쓰기 컴포넌트 이동, 디자인 리뉴얼
  src/App.js
  src/Assets/Board_Enter.png
  src/Pages/Board/GIFBoard.js
  src/Pages/Board/NewBoard.js
  src/Style/WriteBtn.js
  src/Style/WriteWord.js
Labels: feat, design

#52 [FEAT/DESIGN] 인기 예약 조회(백엔드 테스트 미완료)/타임테이블 블록 추가
  src/Pages/Run/ReservationList.js
  src/Pages/Run/TimeTable.js
  src/Pages/Run/TodayPopVids.js
Labels: feat, design

#53 [FEAT] 달리기방 영상, 사용자정보 가져오기
  .env
  package-lock.json
  package.json
  src/Components/Video/YoutubeIframe.js
  src/Pages/Playlist/PlaylistDetail.js
  src/Pages/Run/Running.js
  src/Pages/Video/VideoDetail.js
  src/Style/Running.js
  yarn.lock
Labels: feat, 달리기방

#54 [FEAT] 상세 플레이리스트 조회, 플리 좋아요/신고/삭제
  src/Pages/Playlist/PlaylistDetail.js
  src/Style/Playlist.js
Labels: feat, 플레이리스트

#55 [DESIGN] 새 짤글 쓰기 해시태그 디자인 수정
  src/Pages/Board/GIFBoard.js
  src/Pages/Board/GIFBoardDetail.js
  src/Pages/Board/NewBoard.js
  src/Style/NewBoard.css
Labels: design

#56 [FEAT] 영상 등록 유의사항 내용 등록
  .env
  .idea/.gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/itaseki-front.iml
  .idea/modules.xml
  .idea/vcs.xml
  package.json
  src/Pages/Video/AddNewVideo.js
  src/Pages/Video/VideoDetail.js
  src/Style/Video.js
  yarn.lock
Labels: 영상게시판, feat

#57 [FEAT/DESIGN] 영상, 플레이리스트 키워드 검색 추가
  src/App.js
  src/Assets/Search_Vanner.png
  src/Components/Header.js
  src/Pages/Search/Search.js
  src/Style/WriteBtn.js
Labels: feat, design

#58 [FEAT] 헤더 토글 프로필 이미지&토글 내용
  .idea/workspace.xml
  src/Components/Header.js
  src/Pages/Start/Login.js
  src/Style/Login.js
Labels: feat, 로그인

#60 [DESIGN] 잡담 게시판 최종 디자인으로 수정
  src/Assets/Add_Post.png
  src/Assets/BEST_Commu.png
  src/Assets/Best_Commu.png
  src/Assets/Comment_reply.png
  src/Assets/Enter_Comment.png
  src/Assets/Exit_reply.png
  src/Components/Comment/CommentList.js
  src/Components/Comment/SingleComment.js
  src/Components/Header.js
  src/Components/Modal.js
  src/Pages/Board/Community.js
  src/Pages/Board/CommunityDetail.js
  src/Style/Community.js
Labels: design, 잡담게시판

#61 [FEAT/DESIGN] 타임테이블 수정
  src/Pages/Run/AddReserv.js
  src/Pages/Run/Detail.js
  src/Pages/Run/Reservation.js
  src/Pages/Run/TimeTable.js
  src/Pages/Run/TodayPopVids.js
Labels: feat, design

#62 [FEAT/DESIGN] 플리 모달 3개(플레이리스트에 영상 추가, 새 플레이리스트 생성, 플레이리스트 저장하기)
  .env
  src/Components/Playlist/AddVideoToPlaylistModal.js
  src/Components/Playlist/NewPlaylistModal.js
  src/Components/Playlist/SavePlyModal.js
  src/Components/Video/OneVideo.js
  src/Pages/Playlist/AllPlaylist.js
  src/Pages/Playlist/PlaylistDetail.js
  src/Pages/Playlist/SubscribedPly.js
  src/Pages/Video/AddNewVideo.js
  src/Style/Playlist.js
  src/Style/Video.js
Labels: feat, design, 플레이리스트

#63 [FIX] 상세 플리 게시글 좋아요 표시 오류 수정
  src/Pages/Playlist/PlaylistDetail.js
Labels: fix

#64 [FEAT] 탈퇴하기(백엔드X)
  src/Components/Header.js
Labels: feat, 로그인

#65 [FEAT/DESIGN] 달리기방 채팅 기능&디자인
  src/Components/Chat/ChatContainer.js
  src/Components/Chat/ChatPresenter.js
  src/Components/Header.js
  src/Pages/Run/Running.js
  src/Style/Running.js
Labels: feat, design, 달리기방
