Repository Itaseki/itaseki-front, pull requests merged in 2023-01, with the labels that each got.

#70 [Refactor/Fix/Feat] 색 고정 / 시간 값 수정
  src/Pages/Board/GIFBoard.js
  src/Pages/Board/GIFBoardDetail.js
  src/Pages/Main.js
  src/Pages/Run/AddReserv.js
  src/Pages/Run/Detail.js
  src/Pages/Run/ReservationList.js
  src/Pages/Run/TimeTable.js
  src/Pages/Run/TodayPopVids.js
  src/Style/AddReserv.js
  src/Style/Detail.js
  src/Style/TimeTable.js
  src/Style/TodayPopVids.js
  src/TestData/BoardTestData.js
  src/TestData/MainTest.js
  src/TestData/ReservTest.js
Labels: feat, design, refactor, fix

#72 [FEAT] 새 잡담글 작성 시 이미지 첨부 미리보기 추가
  .idea/workspace.xml
  src/Components/Header.js
  src/Components/Modal.js
  src/Pages/Board/Community.js
  src/Style/Community.js
Labels: feat

#73 [DESIGN] 프로필 디폴트 이미지 변경
  .idea/itaseki-front.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/Assets/User_default_img.png
  src/Components/Header.js
  src/Pages/Run/Running.js
Labels: design

#74 [REFACTOR] 로그인 리팩토링
  .gitignore
  .idea/workspace.xml
  package-lock.json
  package.json
  src/App.js
  src/Components/Header.js
  src/Components/Modal.js
  src/Components/Pagination.js
  src/Components/Playlist/Oneply.js
  src/Components/Token.js
  src/Components/Video/OneVideo.js
  src/Pages/Board/Community.js
  src/Pages/Playlist/AllPlaylist.js
  src/Pages/Playlist/PlaylistDetail.js
  src/Pages/Playlist/SubscribedPly.js
  src/Pages/Start/Login.js
  src/Pages/Start/LoginRedirect.js
  src/Pages/Video/AllVideo.js
  src/Pages/Video/VideoDetail.js
  src/Style/Color.js
  src/Style/Community.js
  src/Style/Running.js
  src/Style/Video.js
  src/Style/color.css
  yarn.lock
Labels: refactor

#75 [REFACTOR] 영상&플리게시판 요소 정렬 코드 리팩토링
  .idea/itaseki-front.iml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
  src/Assets/User_default_img.png
  src/Components/Header.js
  src/Components/Playlist/Oneply.js
  src/Components/Video/OneVideo.js
  src/Pages/Playlist/AllPlaylist.js
  src/Pages/Playlist/SubscribedPly.js
  src/Pages/Run/Running.js
  src/Pages/Video/AllVideo.js
  src/Style/Playlist.js
  src/Style/Video.js
Labels: refactor

#76 [REFACTOR] 영상&플리게시판 전체조회 요청 주소 수정
  src/Pages/Playlist/AllPlaylist.js
  src/Pages/Video/AllVideo.js
Labels: refactor

#77 [FIX] 로그인 토큰 연결
  src/Components/Chat/ChatContainer.js
  src/Components/Comment/CommentList.js
  src/Components/Comment/SingleComment.js
  src/Components/Header.js
  src/Components/Playlist/AddVideoToPlaylistModal.js
  src/Components/Playlist/NewPlaylistModal.js
  src/Components/Playlist/SavePlyModal.js
  src/Components/Token.js
  src/Components/Video/OneVideo.js
  src/Pages/Playlist/PlaylistDetail.js
  src/Pages/Playlist/SubscribedPly.js
  src/Pages/Run/Running.js
  src/Pages/Video/AddNewVideo.js
  src/Pages/Video/AllVideo.js
  src/Pages/Video/VideoDetail.js
Labels: fix

#79 [DESIGN] 시간 표현 수정
  src/Components/Chat/ChatContainer.js
  src/Components/Comment/CommentList.js
  src/Components/Comment/SingleComment.js
  src/Components/Header.js
  src/Components/Playlist/AddVideoToPlaylistModal.js
  src/Components/Playlist/NewPlaylistModal.js
  src/Components/Playlist/SavePlyModal.js
  src/Components/TimeStamp.js
  src/Components/Video/OneVideo.js
  src/Pages/Playlist/PlaylistDetail.js
  src/Pages/Playlist/SubscribedPly.js
  src/Pages/Run/Running.js
  src/Pages/Video/AddNewVideo.js
  src/Pages/Video/AllVideo.js
  src/Pages/Video/VideoDetail.js
Labels: design

#80 [FIX] 플레이리스트 상세게시물 조회 불가능 오류 수정
  src/Pages/Playlist/PlaylistDetail.js
Labels: fix

#81 [REFACTOR] 신고 기능 보완
  src/Components/Comment/SingleComment.js
  src/Pages/Playlist/PlaylistDetail.js
  src/Pages/Video/AddNewVideo.js
  src/Pages/Video/VideoDetail.js
Labels: refactor

#84 [Design] 달리기 대기 페이지 디자인 수정(타임테이블 제외)
  src/Assets/Guide_Btn.png
  src/Assets/Main_logo.png
  src/Assets/Main_logo_dark.png
  src/Assets/Reservation_bg.png
  src/Components/Header.js
  src/Pages/Run/Reservation.js
  src/Pages/Run/ReservationList.js
  src/Pages/Run/TodayPopVids.js
  src/Style/AddReserv.js
  src/Style/Reservation.js
  src/Style/ReservationList.js
  src/Style/StyledDiv.js
  src/Style/TimeTable.js
  src/Style/TodayPopVids.js
Labels: design

#85 [Fix] 타임테이블 색 수정, 영상 적용 여부 팝업 수정
  src/Pages/Run/AddReserv.js
  src/Pages/Run/TimeTable.js
Labels: fix

#86 [Design] 타임테이블 디자인 변경
  src/Pages/Run/TimeTable.js
  src/Style/TimeTable.js
Labels: design

#88 [FIX] 로그아웃 수정
  src/Components/Header.js
Labels: fix

#89 [FIX] Context api 사용하여 사용자 정보 저장 및 호출
  src/App.js
  src/Components/Comment/CommentList.js
  src/Components/Comment/SingleComment.js
  src/Components/Header.js
  src/_contextAPI/Store.js
  src/_contextAPI/UserContext.js
Labels: fix

#90 [Design] 메인 페이지 디자인 변경
  src/Assets/Main_bg.png
  src/Components/Header.js
  src/Pages/Main.js
  src/Style/Main.js
Labels: design

#92 fix: 배경 이미지 제거(로딩 시간 문제)
  src/Assets/MainPage_Logo.png
  src/Assets/Main_logo.png
  src/Assets/Main_logo_dark.png
  src/Style/Main.js
  src/Style/Reservation.js
Labels: fix

#94 [Design] 메인 페이지 디자인 변경
  package-lock.json
  package.json
  src/App.js
  src/Assets/Guideline_Btn.png
  src/Assets/PopPlaylist.png
  src/Assets/Run_Btn.png
  src/Assets/Sleepy_Eye.png
  src/Assets/Video_Btn.png
  src/Components/Footer.js
  src/Components/Header.js
  src/Pages/Main.js
  src/Pages/Member/Center.js
  src/Pages/Member/Guide.js
  src/Style/Main.js
  yarn.lock
Labels: design

#95 [FIX] 로그인 시 프로필 이미지 바로 안 뜨는 오류 수정
  src/Components/Header.js
  src/Pages/Start/LoginRedirect.js
  yarn.lock
Labels: fix

#96 [DESIGN] 상단 헤더 프로필 조회 모달창 디자인 수정
  src/Components/Header.js
  src/Style/Color.js
Labels: design

#97 [DESIGN] 마이페이지 디자인
  src/App.js
  src/Assets/Mypage_GotoSavedply.png
  src/Assets/Mypage_GotoSetting.png
  src/Assets/Mypage_eye1.png
  src/Assets/Mypage_eye2.png
  src/Assets/kakao_login_large_wide.png
  src/Components/Mypage/MyPly.js
  src/Components/Mypage/MyVideo.js
  src/Components/Mypage/Pagination.js
  src/Pages/Member/MyPage.js
  src/Pages/Member/MySavedPly.js
  src/Style/MyPage.js
Labels: design

#98 [FEAT] 마이페이지 내용 불러오기 & 전체 영상 페이지 url 변경
  src/App.js
  src/Components/Header.js
  src/Components/Mypage/MyComment.js
  src/Components/Mypage/MyVideo.js
  src/Components/Mypage/Pagination.js
  src/Components/Video/OneVideo.js
  src/Pages/Member/MyPage.js
  src/Pages/Member/MySavedPly.js
Labels: feat

#99 [FEAT] 로그아웃, 탈퇴 및 마이페이지 프로필 조회
  package-lock.json
  package.json
  src/Components/Header.js
  src/Pages/Member/MyPage.js
  src/Style/MyPage.js
  yarn.lock
Labels: feat

#100 [FIX/DESIGN] 플레이리스트 게시판 오류 수정 및 디자인 변경
  src/Assets/Ply_main.png
  src/Assets/Ply_preview.png
  src/Components/Pagination.js
  src/Components/Playlist/AddVideoToPlaylistModal.js
  src/Components/Playlist/NewPlaylistModal.js
  src/Components/Playlist/Oneply.js
  src/Components/Playlist/SavePlyModal.js
  src/Pages/Playlist/AllPlaylist.js
  src/Pages/Playlist/PlaylistDetail.js
  src/Pages/Playlist/SubscribedPly.js
  src/Pages/Video/AllVideo.js
  src/Style/Community.js
  src/Style/Playlist.js
  src/Style/Video.js
Labels: design, fix

#101 [DESIGN] 영상게시판 디자인 수정
  src/Assets/Video_main.png
  src/Components/Playlist/Oneply.js
  src/Components/Video/OneVideo.js
  src/Pages/Playlist/AllPlaylist.js
  src/Pages/Video/AddNewVideo.js
  src/Pages/Video/AllVideo.js
  src/Pages/Video/VideoDetail.js
  src/Style/Video.js
Labels: design

#102 [Feat/Design]
  src/Pages/Main.js
  src/Style/Main.js
  yarn.lock
Labels: feat, design

#103 [DESIGN] 프로필 모달창&댓글&프로필 디폴트 이미지&마이페이지 디자인 수정
  src/Assets/User_default_img.png
  src/Components/Comment/CommentList.js
  src/Components/Comment/SingleComment.js
  src/Components/Header.js
  src/Components/Mypage/MyPly.js
  src/Components/Mypage/MyVideo.js
  src/Pages/Member/MyPage.js
  src/Style/Community.js
Labels: design

#105 [Feat] 검색 페이지 구현
  src/Assets/Three_Rabbits.png
  src/Pages/Search/Search.js
  src/Style/Search.js
Labels: feat, design

#106 [Feat/Fix] 검색 결과 수정
  src/Pages/Search/Search.js
  src/Style/Search.js
Labels: feat, design, fix
